create table if not exists inventory_filaments (
    id bigint generated by default as identity primary key,
    type text not null default 'PLA Basic',
    brand text not null default '',
    color text not null default '',
    weight_grams numeric not null default 0,
    cost_per_kg numeric not null default 0,
    notes text not null default '',
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists inventory_materials (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null default 'Hardware',
    quantity numeric not null default 0,
    unit text not null default 'pcs',
    bulk_price numeric not null default 0,
    cost_per_unit numeric not null default 0,
    notes text not null default '',
    created_at timestamptz not null default timezone('utc'::text, now()),
    updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table inventory_filaments enable row level security;
alter table inventory_materials enable row level security;

create policy "inventory_filaments_select_all"
on inventory_filaments
for select
to anon, authenticated
using (true);

create policy "inventory_filaments_insert_all"
on inventory_filaments
for insert
to anon, authenticated
with check (true);

create policy "inventory_filaments_update_all"
on inventory_filaments
for update
to anon, authenticated
using (true)
with check (true);

create policy "inventory_filaments_delete_all"
on inventory_filaments
for delete
to anon, authenticated
using (true);

create policy "inventory_materials_select_all"
on inventory_materials
for select
to anon, authenticated
using (true);

create policy "inventory_materials_insert_all"
on inventory_materials
for insert
to anon, authenticated
with check (true);

create policy "inventory_materials_update_all"
on inventory_materials
for update
to anon, authenticated
using (true)
with check (true);

create policy "inventory_materials_delete_all"
on inventory_materials
for delete
to anon, authenticated
using (true);
