create table if not exists inventory_purchase_history (
    id bigint generated by default as identity primary key,
    date timestamptz not null,
    item_type text not null,
    item_id bigint,
    item_label text not null,
    item_category text,
    unit_label text,
    quantity_added numeric not null default 0,
    purchase_cost numeric not null default 0,
    prev_cost_per_unit numeric,
    new_cost_per_unit numeric,
    prev_quantity numeric,
    new_quantity numeric,
    filament_id bigint,
    filament_label text,
    grams_added numeric,
    prev_cost_per_kg numeric,
    new_cost_per_kg numeric,
    prev_weight_grams numeric,
    new_weight_grams numeric,
    created_at timestamptz not null default timezone('utc'::text, now())
);

alter table inventory_purchase_history enable row level security;

create policy "inventory_purchase_history_select_all"
on inventory_purchase_history
for select
to anon, authenticated
using (true);

create policy "inventory_purchase_history_insert_all"
on inventory_purchase_history
for insert
to anon, authenticated
with check (true);

create policy "inventory_purchase_history_update_all"
on inventory_purchase_history
for update
to anon, authenticated
using (true)
with check (true);

create policy "inventory_purchase_history_delete_all"
on inventory_purchase_history
for delete
to anon, authenticated
using (true);

create index if not exists inventory_purchase_history_date_idx
on inventory_purchase_history (date desc);
